### PR TITLE
update kopano logos

### PR DESCRIPTION
**Pull request by fbartels**
Hello @peterbeck ,

I've taken the liberty of replacing the Kopano logos with their official counterparts (the ol extension logo was even only the general kopano logo). this also updates the filename and type of the koe logo.

How is your experience with chocolatey so far? (you've seem to be using it for a while already). I did take a small glance into providing an official koe package a while back, but never really got it off the ground.

If you want to push an app to the official chocolatey listing let me know how and if I can help.

### CODE REVIEW

**Comment by peterbeck** [comment]
Hi Felix,

thanks for the correct logos. I am using chocolatey mainly because of their Puppet integration. In general I am anything else than a Windows admin but it's hard to get around, especially with Clients. As I am a heavy Puppet user it was quiet obvious for me to use chocolatey. They say it's apt for Windows. But in my opinion it's faaaaar away from that quality.

Yeah, I know, publishing packages to the choco repositories is a little bit frustrating. That was the reason i set up my own repo with [phpnuget](http://www.kendar.org/?p=/dotnet/phpnuget). It's not perfect, but as far as I know one of the only servers running mainly on GNU/Linux. And as one of the only FSFE fellows from Liechtenstein, this is important for me ;-)
And also, lots of the packaging in the choco repositories does not meet my standards, I had to repackage some things (deleting uninstall links, desktop icons etc)

I've just uploaded the package "kopano-ol-extension-nightly" to the choco repo, it's now pending in review. I think I should give you moderation rights on that package, what's your username over there ?
I hope they'll approve it ;-)

Best Regards 
Peter

**Comment by fbartels** [comment]
Hi Peter,

thanks for uploading the package, looks quite good already imho (although I did not yet get to testing it). My previous tests were only local but I just now created an account in their system. username over there is  fbartels".

Thanks

**Comment by peterbeck** [comment]
Hi Felix, 

the package fails because my package is testing for installed Outlook >= 2013:

> 2017-08-01 08:14:40,079 1820 [INFO ] - unsupported (or no) Outlook Version detected
> 2017-08-01 08:14:40,126 1820 [ERROR] - ERROR: ScriptHalted

Is it possible to install KOE even there is no Outlook present during setup or does KOE also fail without Outlook ?
If it's working, when OL will be installed later, I'll remove that condition from my package...
BTW: Upload to github follows soon...
BTW2: I named the package kopano-ol-extension-nightly, as it's not that conveniant if using prereleases...

Regards
Peter

**Comment by peterbeck** [comment]
Packages are now uploaded here to github

**Comment by fbartels** [comment]
> Is it possible to install KOE even there is no Outlook present during setup or does KOE also fail without Outlook ?

No, afaik this is not possible. KOE requires both .net >=4.5.2 and some Office Visual Studio stuff that is only available if Office is installed.

> Packages are now uploaded here to github

thanks. and also for adding me as a maintainer to the koe and deskapp apps.

**Pull request merged**
